spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/moiza__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: lldj        # ?? DB ??
    password: ${MYSQL_PW} # ?? DB ??
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 50
  sendgrid:
    api-key: ${SENDGRID_MOIZA}
custom:
  jwt:
    secretKey: thissecretkeyisfordevandtestdontusethissecretkeyinrealproduction
