spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect:
    hibernate:
      ddl-auto: create
logging:
  level:
    org.mongodb.driver: DEBUG
custom:
  site:
    baseUrl: http://localhost:8080
    calculatorUrl: http://localhost:8081