spring:
  jpa:
    hibernate:
      ddl-auto: update    # 앱 처음 시작 시 생기는 오류는 무시해도 됨
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.17.0.1:3306/moiza__prod?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
custom:
  site:
    baseUrl: https://moiza.online