spring:
  jpa:
    hibernate:
      ddl-auto: create    # 앱 처음 시작 시 생기는 오류는 무시해도 됨
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/moiza__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
custom:
  site:
    baseUrl: http://localhost:8080
    calculatorUrl: http://localhost:8081
  webdriver:
    port: 9515