spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    active: dev
    include: secret
  security:
    oauth2:
      client:
        registration:
          kakao:
            scope: profile_nickname, account_email, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 50
        dialect: org.hibernate.dialect.MySQL8Dialect
custom:
  site:
    baseUrl: