spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    active: dev
    include: secret
  security:
    oauth2:
      client:
        registration:
          google:
            scope: https://www.googleapis.com/auth/calendar.events
            authorization-grant-type: authorization_code
            auth-uri: 'https://accounts.google.com/o/oauth2/v2/auth'
            token-uri: 'https://oauth2.googleapis.com/token'
            redirect-uri: 'http://localhost:8080/callback'
            response-type: code
          kakao:
            scope: profile_nickname, account_email, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: ${custom.site.baseUrl}/login/oauth2/code/kakao
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  thymeleaf:
    prefix: classpath:/templates/
custom:
  mail:
    sender: mouse4786@gmail.com
  site:
    baseUrl: